"""add indexes

Revision ID: 804982408b1d
Revises: 22edcae794f7
Create Date: 2026-07-14 11:07:58.024408
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '804982408b1d'
down_revision: Union[str, None] = '22edcae794f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_logs', schema=None) as batch_op:
        batch_op.create_index('ix_logs_mailbox_created', ['mailbox_id', 'created_at'], unique=False)
        batch_op.create_index('ix_logs_user_created', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index('ix_invitations_org', ['org_id'], unique=False)

    with op.batch_alter_table('mailboxes', schema=None) as batch_op:
        batch_op.create_index('ix_mailboxes_org', ['org_id'], unique=False)
        batch_op.create_index('ix_mailboxes_user', ['user_id'], unique=False)

    with op.batch_alter_table('org_members', schema=None) as batch_op:
        batch_op.create_index('ix_org_members_user', ['user_id'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index('ix_orgs_owner', ['owner_user_id'], unique=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_refresh_user', ['user_id'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_stripe_customer', ['stripe_customer_id'], unique=False)

    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index('ix_syslogs_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_syslogs_timestamp')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_stripe_customer')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_user')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('ix_orgs_owner')

    with op.batch_alter_table('org_members', schema=None) as batch_op:
        batch_op.drop_index('ix_org_members_user')

    with op.batch_alter_table('mailboxes', schema=None) as batch_op:
        batch_op.drop_index('ix_mailboxes_user')
        batch_op.drop_index('ix_mailboxes_org')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index('ix_invitations_org')

    with op.batch_alter_table('interaction_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_logs_user_created')
        batch_op.drop_index('ix_logs_mailbox_created')

    # ### end Alembic commands ###
